const questions = [
    {"question": "What is the capital of France?", "answer": "Paris"},
    {"question": "Which planet is known as the Red Planet?", "answer": "Mars"},
    {"question": "What is the largest mammal?", "answer": "Blue Whale"},
    {"question": "Who wrote 'Romeo and Juliet'?", "answer": "William Shakespeare"},
    {"question": "What's the smallest prime number?", "answer": "2"},
    {"question": "Who was the first President of the United States?", "answer": "George Washington"},
    {"question": "What is the symbol for gold on the periodic table?", "answer": "Au"},
    {"question": "What's the tallest mountain in the world?", "answer": "Mount Everest"},
    {"question": "What is the square root of 144?", "answer": "12"},
    {"question": "What's the capital city of Spain?", "answer": "Madrid"},
    {"question": "Which country is known as the Land of the Rising Sun?", "answer": "Japan"},
    {"question": "Who is the author of 'The Hobbit'?", "answer": "J.R.R. Tolkien"},
    {"question": "What's the largest planet in the Solar System?", "answer": "Jupiter"},
    {"question": "What is the chemical symbol for water?", "answer": "H2O"},
    {"question": "What year did the Titanic sink?", "answer": "1912"},
    {"question": "What's the capital of Canada?", "answer": "Ottawa"},
    {"question": "Who painted the Mona Lisa?", "answer": "Leonardo da Vinci"},
    {"question": "Which gas do plants absorb from the atmosphere?", "answer": "Carbon Dioxide"},
    {"question": "What is the currency of Japan?", "answer": "Yen"},
    {"question": "Who was the first woman to fly solo across the Atlantic?", "answer": "Amelia Earhart"},
    {"question": "What's the national flower of Japan?", "answer": "Cherry Blossom"},
    {"question": "Which bone is the longest in the human body?", "answer": "Femur"},
    {"question": "Who invented the telephone?", "answer": "Alexander Graham Bell"},
    {"question": "What's the smallest planet in the Solar System?", "answer": "Mercury"},
    {"question": "What's the capital city of Brazil?", "answer": "Brasília"},
    {"question": "What's the atomic number of gold?", "answer": "79"},
    {"question": "Which ocean is the largest on Earth?", "answer": "Pacific Ocean"},
    {"question": "What's the capital of Australia?", "answer": "Canberra"},
    {"question": "Who discovered penicillin?", "answer": "Alexander Fleming"},
    {"question": "What's the boiling point of water in Celsius?", "answer": "100"}
];
console.log(`${questions.length} questions are loaded!`);